// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLbdzca0CoJL_AavFRi3zwkPVfI57U6FA',
    appId: '1:386603909463:web:c6cb5c3fafa81dd9c5be12',
    messagingSenderId: '386603909463',
    projectId: 'teste-rgr-503da',
    authDomain: 'teste-rgr-503da.firebaseapp.com',
    storageBucket: 'teste-rgr-503da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOKOnPIUTCi1goEznuFAWrEzrMUOBBZ4',
    appId: '1:386603909463:android:24d263376a7316fec5be12',
    messagingSenderId: '386603909463',
    projectId: 'teste-rgr-503da',
    storageBucket: 'teste-rgr-503da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh4XsKOKoRz2O7VRMkqS-B2xnwplUUO8s',
    appId: '1:386603909463:ios:d00c778b803f03d7c5be12',
    messagingSenderId: '386603909463',
    projectId: 'teste-rgr-503da',
    storageBucket: 'teste-rgr-503da.firebasestorage.app',
    iosBundleId: 'com.example.rgr',
  );
}
